name: fluix
description: An HUB for UI Designs with CODE

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_database: ^3.1.6
  firebase_storage: ^3.1.6
  flutter_spinkit:
  bordered_text:
  dynamic_theme:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
  
  fonts:
    - family: Dosis
      fonts:
      - asset: fonts/Dosis-ExtraBold.ttf