name: fluix
description: An HUB for UI Designs with CODE

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_core:
  cloud_firestore:
  firebase_database:
  firebase_storage:
  flutter_spinkit:
  bordered_text:
  dynamic_theme:
  provider:
  flutter_staggered_grid_view:
  transparent_image:
  wave_drawer:
  cached_network_image:
  google_fonts:
  curved_navigation_bar:
  convex_bottom_bar:
  circle_bottom_navigation:
  google_nav_bar:
  line_icons:
  flutter_bloc:
  hidden_drawer_menu:
  foldable_sidebar:
  swipedetector:
  flare_flutter:
  smart_flare:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
  
  fonts:
    - family: Dosis
      fonts:
      - asset: fonts/Dosis-ExtraBold.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700